const appIcon1 = `<svg fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 18h.01M8 21h8a2 2 0 002-2V5a2 2 0 00-2-2H8a2 2 0 00-2 2v14a2 2 0 002 2z"></path></svg>`;
const appIcon2 = `<svg fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 3v2m6-2v2M9 19v2m6-2v2M5 9H3m2 6H3m18-6h-2m2 6h-2M7 19h10a2 2 0 002-2V7a2 2 0 00-2-2H7a2 2 0 00-2 2v10a2 2 0 002 2zM9 9h6v6H9V9z"></path></svg>`;
const appIcon3 = `<svg fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M13 10V3L4 14h7v7l9-11h-7z"></path></svg>`;

const mobileAppLocations = [
  { folder: 'mobile-apps-sandton', name: 'Sandton', hub: 'Fintech & Enterprise Banking Capital', landmarks: 'Sandton City, Alice Lane, Sandton Gautrain Station', arterials: 'Rivonia Road, Sandton Drive, Katherine Street, M1', lat: -26.1075, lng: 28.0567, suburbs: ['Sandown', 'Morningside', 'Inanda', 'Benmore', 'Riverclub'], focus: 'Fintech mobile apps, micro-lending portals, corporate wealth dashboards, and executive banking solutions.' },
  { folder: 'mobile-apps-rosebank', name: 'Rosebank', hub: 'Tech Startup & Venture District', landmarks: 'The Zone @ Rosebank, Rosebank Link, Oxford Parks', arterials: 'Oxford Road, Jan Smuts Avenue, Bolton Road', lat: -26.1458, lng: 28.0417, suburbs: ['Parkwood', 'Dunkeld', 'Houghton Estate', 'Killarney', 'Saxonwold'], focus: 'Consumer on-demand apps, social marketplaces, subscription platforms, and startup MVP applications.' },
  { folder: 'mobile-apps-melrose-arch', name: 'Melrose Arch', hub: 'Enterprise & SaaS Technology Hub', landmarks: 'Melrose Arch Precinct, Stanlib Node, High Street', arterials: 'M1 Highway, Corlett Drive, Athol Oaklands Road', lat: -26.1339, lng: 28.0683, suburbs: ['Melrose North', 'Waverley', 'Birnam', 'Bramley', 'Oaklands'], focus: 'Enterprise mobile SaaS, B2B workflow automations, corporate communication apps, and smart business portals.' },
  { folder: 'mobile-apps-waterfall-city', name: 'Waterfall City', hub: 'HealthTech, Logistics & Smart City Hub', landmarks: 'Mall of Africa, Waterfall Corporate Campus, Netcare Waterfall', arterials: 'Allandale Road, N1 Highway, Maxwell Drive, K101', lat: -26.0134, lng: 28.1062, suburbs: ['Waterfall Country Estate', 'Kikuyu', 'Jukskei View', 'Vorna Valley', 'Barbeque Downs'], focus: 'Healthtech patient apps, telematics mobile dashboards, logistics dispatch apps, and smart city services.' },
  { folder: 'mobile-apps-bryanston', name: 'Bryanston', hub: 'Digital Agency & SaaS Headquarters', landmarks: 'Bryanston Shopping Centre, Nicolway, Ballyclare Node', arterials: 'William Nicol Drive, Main Road, Bryanston Drive, N1', lat: -26.0500, lng: 28.0167, suburbs: ['Epsom Downs', 'Riverclub', 'Petervale', 'Douglasdale', 'Hurlingham'], focus: 'Marketing automation apps, custom CRM mobile portals, brand loyalty apps, and e-learning platforms.' },
  { folder: 'mobile-apps-menlyn-maine', name: 'Menlyn Maine', hub: 'Pretoria Green City & Tech Precinct', landmarks: 'Menlyn Maine Central Square, Time Square Casino, Amarand Ave', arterials: 'N1 Highway, Atterbury Road, Garsfontein Road, Dallas Ave', lat: -25.7875, lng: 28.2800, suburbs: ['Garsfontein', 'Faerie Glen', 'Newlands', 'Waterkloof Glen', 'Ashlea Gardens'], focus: 'Government tech solutions, corporate mobile reporting, compliance auditing apps, and enterprise platforms.' },
  { folder: 'mobile-apps-pretoria-east', name: 'Pretoria East', hub: 'MedTech & High-Tech Research Hub', landmarks: 'Innovation Hub, CSIR Campus, Wilgers Hospital', arterials: 'N4 Highway, Lynnwood Road, Solomon Mahlangu Drive', lat: -25.7667, lng: 28.3167, suburbs: ['Faerie Glen', 'Silver Lakes', 'Equestria', 'Die Wilgers', 'Wapadrand'], focus: 'Clinical trial apps, medical practice management, telemetry monitoring, and agricultural sensor apps.' },
  { folder: 'mobile-apps-centurion', name: 'Centurion', hub: 'Defense, IoT & Telematics Hub', landmarks: 'Centurion Mall, Highveld Techno Park, Supersport Park', arterials: 'N1 Highway, N14, John Vorster Drive, Botha Avenue', lat: -25.8600, lng: 28.1889, suburbs: ['Highveld', 'Doringkloof', 'Zwartkop', 'Eldoraigne', 'Clubview'], focus: 'IoT hardware integration apps, vehicle telematics, security tracking apps, and defense tech systems.' },
  { folder: 'mobile-apps-midrand', name: 'Midrand', hub: 'Enterprise Logistics & Telecoms Center', landmarks: 'Grand Central Airport, Gallagher Convention Centre', arterials: 'N1 Freeway, Old Pretoria Road (R101), New Road, Lever Rd', lat: -25.9989, lng: 28.1264, suburbs: ['Halfway House', 'Carlswald', 'Kyalami', 'Noordwyk', 'Crowthorne'], focus: 'Warehouse inventory barcode apps, driver delivery portals, field service management, and ERP mobile tools.' },
  { folder: 'mobile-apps-johannesburg-cbd', name: 'Johannesburg CBD', hub: 'Retail & Inclusive Banking Center', landmarks: 'Carlton Centre, Bank City, Newtown Cultural Precinct', arterials: 'M1 Highway, M2 Freeway, Commissioner Street, Rissik St', lat: -26.2041, lng: 28.0473, suburbs: ['Marshalltown', 'Newtown', 'Braamfontein', 'Fordsburg', 'Selby'], focus: 'QR code payment apps, agency banking tools, retail reward wallets, and mass transit ticketing apps.' },
  { folder: 'mobile-apps-fourways', name: 'Fourways', hub: 'Consumer & On-Demand Lifestyle Hub', landmarks: 'Fourways Mall, Montecasino, Design Quarter', arterials: 'William Nicol Drive, Witkoppen Road, Cedar Road', lat: -26.0167, lng: 28.0000, suburbs: ['Lonehill', 'Dainfern', 'Broadacres', 'Craigavon', 'Paulshof'], focus: 'Food & grocery delivery apps, concierge booking platforms, fitness tracking apps, and event ticketing.' },
  { folder: 'mobile-apps-bedfordview', name: 'Bedfordview', hub: 'B2B Wholesale & Logistics Apps', landmarks: 'Eastgate Shopping Centre, Bedford Centre, Gillooly’s', arterials: 'R24 Airport Highway, N3 Highway, N12, Nicol Road', lat: -26.1745, lng: 28.1340, suburbs: ['St Andrews', 'Morninghill', 'Oriel', 'Bedford Park', 'Essexwold'], focus: 'B2B ordering apps, client catalog portals, wholesale billing mobile apps, and trade technician tools.' },
  { folder: 'mobile-apps-edenvale', name: 'Edenvale', hub: 'Field Service & Trade Dispatch Hub', landmarks: 'Greenstone Shopping Centre, Stoneridge, Van Riebeeck Ave', arterials: 'Modderfontein Road, N3 Freeway, Van Riebeeck Ave', lat: -26.1314, lng: 28.1432, suburbs: ['Greenstone Hill', 'Modderfontein', 'Dowerglen', 'Hurlyvale', 'Eastleigh'], focus: 'Job scheduling apps, mobile invoicing for contractors, field service dispatch, and customer booking apps.' },
  { folder: 'mobile-apps-benoni', name: 'Benoni', hub: 'Industrial Operations & Trade Mobile Tools', landmarks: 'Lakeside Mall, Northmead Square, Snake Road Corridor', arterials: 'N12 Freeway, R23, Snake Road, Tom Jones Street', lat: -26.1714, lng: 28.2436, suburbs: ['Rynfield', 'Northmead', 'Lakefield', 'Farrarmere', 'Crystal Park'], focus: 'Trade technician tracking, fleet maintenance loggers, industrial inspection apps, and local SME tools.' },
  { folder: 'mobile-apps-boksburg', name: 'Boksburg', hub: 'E-Commerce & Retail Delivery Hub', landmarks: 'East Rand Mall, K90 Centre, Trichardts Road', arterials: 'N12 Highway, R21, Atlas Road, Rondebult Road', lat: -26.2139, lng: 28.1818, suburbs: ['Bartlett', 'Sunward Park', 'Beyers Park', 'Parkrand', 'Boksburg North'], focus: 'E-commerce mobile store apps, click-and-collect portals, customer loyalty reward apps, and delivery trackers.' },
  { folder: 'mobile-apps-randburg', name: 'Randburg', hub: 'Media, Broadcasting & Entertainment Apps', landmarks: 'Multichoice City, Cresta Shopping Centre, Brightwater', arterials: 'N1 Western Bypass, Bram Fischer Drive, Malibongwe Dr', lat: -26.0918, lng: 27.9174, suburbs: ['Ferndale', 'Bordeaux', 'Cresta', 'Northcliff', 'Blairgowrie'], focus: 'Video streaming apps, podcast player platforms, casting call booking tools, and media content portals.' },
  { folder: 'mobile-apps-rivonia', name: 'Rivonia', hub: 'LegalTech & Enterprise Mobile Portals', landmarks: 'Rivonia Boulevard, 12th Avenue Commercial Strip', arterials: 'Rivonia Road, N1 Highway, 12th Avenue, Witkoppen Rd', lat: -26.0583, lng: 28.0594, suburbs: ['Edenburg', 'Morningside Manor', 'Woodmead', 'Gallo Manor', 'Sunninghill'], focus: 'Legal practice management apps, client document signature portals, billable hour tracking, and audit apps.' },
  { folder: 'mobile-apps-illovo', name: 'Illovo', hub: 'WealthTech & Private Executive Apps', landmarks: 'Illovo Boulevard, Thrupps Centre, Fricker Road', arterials: 'Oxford Road, Corlett Drive, Central Avenue', lat: -26.1333, lng: 28.0500, suburbs: ['Melrose', 'Inanda', 'Rosebank', 'Dunkeld', 'Rivonia'], focus: 'Private wealth portfolio apps, executive KPI dashboards, confidential investor portals, and M&A data rooms.' },
  { folder: 'mobile-apps-woodmead', name: 'Woodmead', hub: 'Telecommunications & Enterprise Mobility', landmarks: 'Woodmead Commercial Park, 3M Node, Retail Park', arterials: 'M1 Highway, N1 Highway, Woodmead Drive, Bowling Ave', lat: -26.0556, lng: 28.0778, suburbs: ['Khyber Rock', 'Buccleuch', 'Gallo Manor', 'Sunninghill', 'Kelvin'], focus: 'Enterprise workforce mobility, field engineer apps, mobile VoIP integrations, and asset tracking portals.' },
  { folder: 'mobile-apps-hyde-park', name: 'Hyde Park', hub: 'Luxury Concierge & Real Estate Apps', landmarks: 'Hyde Park Corner, Jan Smuts Avenue, 6th Road', arterials: 'Jan Smuts Avenue, William Nicol Drive, 6th Rd', lat: -26.1264, lng: 28.0353, suburbs: ['Dunkeld', 'Craighall Park', 'Illovo', 'Inanda', 'Sandhurst'], focus: 'Luxury lifestyle concierge apps, private real estate showcase apps, art auction portals, and VIP booking tools.' },
  { folder: 'mobile-apps-morningside', name: 'Morningside', hub: 'Medical Practice & Telehealth Apps', landmarks: 'Morningside Clinic, The Wedge, Outspan Road', arterials: 'Rivonia Road, Outspan Road, Summit Road, Alon Rd', lat: -26.0825, lng: 28.0622, suburbs: ['Sandown', 'Riverclub', 'Duxberry', 'Benmore Gardens', 'Bryanston East'], focus: 'Telehealth video consultation apps, digital prescription managers, patient health record portals, and lab trackers.' },
  { folder: 'mobile-apps-northcliff', name: 'Northcliff', hub: 'SME Management & Education Apps', landmarks: 'Northcliff Corner, Beyers Naudé Node, Impala Centre', arterials: 'Beyers Naudé Drive, 14th Avenue, N1 Highway', lat: -26.1500, lng: 27.9667, suburbs: ['Fairland', 'Blackheath', 'Berario', 'Valeriedene', 'Cresta'], focus: 'Private school parent portals, student learning apps, SME customer self-service apps, and billing portals.' },
  { folder: 'mobile-apps-roodepoort', name: 'Roodepoort', hub: 'Field Dispatch & Logistics Driver Apps', landmarks: 'Clearwater Mall, Westgate, Constantia Office Park', arterials: 'Hendrik Potgieter Road, Ontdekkers Road, N1 Highway', lat: -26.1625, lng: 27.8725, suburbs: ['Constantia Kloof', 'Helderkruin', 'Florida', 'Wilgeheuwel', 'Little Falls'], focus: 'Route navigation apps, proof-of-delivery barcode scanners, driver inspection checklists, and mobile POS.' },
  { folder: 'mobile-apps-krugersdorp', name: 'Krugersdorp', hub: 'AgriTech & Mining Safety Mobile Apps', landmarks: 'Key West Mall, Cradlestone Mall, Paardekraal Node', arterials: 'N14 Highway, R28, Ontdekkers Road, Robert Broom Dr', lat: -26.1000, lng: 27.7667, suburbs: ['Noordheuwel', 'Kenmare', 'Monument', 'Silverfields', 'Rant-en-Dal'], focus: 'Mining safety compliance checklists, precision farming telemetry, soil moisture monitors, and equipment loggers.' },
  { folder: 'mobile-apps-alberton', name: 'Alberton', hub: 'Courier & Warehouse Mobile Systems', landmarks: 'Alberton City, Newmarket Commercial, Ring Road', arterials: 'N12 Freeway, R59 Freeway, Voortrekker Road', lat: -26.2667, lng: 28.1167, suburbs: ['New Redruth', 'Florentia', 'Raceview', 'Meyersdal', 'Brackenhurst'], focus: 'Warehouse barcode picking apps, courier dispatch portals, trade invoicing apps, and delivery confirmation tools.' },
  { folder: 'mobile-apps-kempton-park', name: 'Kempton Park', hub: 'Aviation, Freight & Customs Portals', landmarks: 'OR Tambo International, Freight Complex, Festival Mall', arterials: 'R21 Highway, R24 Freeway, CR Swart Drive', lat: -26.1000, lng: 28.2333, suburbs: ['Spartan', 'Isando', 'Rhodesfield', 'Aston Manor', 'Glen Marais'], focus: 'Air cargo tracking apps, customs clearance document portals, crew scheduling tools, and freight status apps.' },
  { folder: 'mobile-apps-germiston', name: 'Germiston', hub: 'Supply Chain & Heavy Transport Apps', landmarks: 'Rand Airport, Driehoek Industrial, Golden Walk', arterials: 'N3 Highway, N12 Freeway, M2 Highway, Rand Airport Rd', lat: -26.2167, lng: 28.1667, suburbs: ['Lambton', 'Primrose', 'Wadeville', 'Albemarle', 'Delville'], focus: 'Heavy fleet maintenance trackers, fuel loggers, transport dispatch portals, and industrial warehouse apps.' },
  { folder: 'mobile-apps-midstream', name: 'Midstream', hub: 'Smart Estate & Security Access Apps', landmarks: 'Midstream Estate Security Gate, Mediclinic, Square', arterials: 'N1 Highway, Brakfontein Road, R101, Midstream Drive', lat: -25.9167, lng: 28.2000, suburbs: ['Midfield Estate', 'Midlands Estate', 'Midstream Ridge', 'Heritage Hill', 'Olifantsfontein'], focus: 'Visitor QR access control apps, smart home utility dashboards, community marketplace apps, and panic alerts.' },
  { folder: 'mobile-apps-lynnwood', name: 'Lynnwood', hub: 'Research & Professional Practice Apps', landmarks: 'Lynnwood Bridge, CSIR, Glenfair Boulevard', arterials: 'Lynnwood Road, N1 Highway, Meiring Naudé Road', lat: -25.7667, lng: 28.2833, suburbs: ['Lynnwood Ridge', 'Lynnwood Manor', 'Menlo Park', 'Die Wilgers', 'Murrayfield'], focus: 'Research data collection tools, medical specialist portals, engineering calculation apps, and IP dashboards.' },
  { folder: 'mobile-apps-silver-lakes', name: 'Silver Lakes', hub: 'Lifestyle & Country Club Management', landmarks: 'Silver Lakes Clubhouse, Hazeldean Node, Lynnwood East', arterials: 'Lynnwood Road, Solomon Mahlangu Drive, N4 Highway', lat: -25.7722, lng: 28.3611, suburbs: ['Hazeldean', 'Six Fountains', 'Equestria', 'Willow Acres', 'Tijger Valley'], focus: 'Golf tee-time booking apps, private member portals, restaurant ordering, and gated estate concierge systems.' }
];

const mobileAppAreas = mobileAppLocations.map(loc => ({
  folder: loc.folder,
  locality: loc.name,
  serviceName: 'Mobile App Development',
  serviceBadge: 'Mobile Software Studio',
  title: `Mobile App Development ${loc.name} | Toran Digital`,
  desc: `Custom iOS & Android mobile app development in ${loc.name}. Flutter, React Native, and native mobile apps engineered for speed, security, and scale.`,
  h1_prefix: `Enterprise Mobile App Development in`,
  h1_highlight: loc.name,
  hero_desc: `Architecting scalable iOS, Android, and cross-platform mobile applications for high-growth enterprises and innovative startups in ${loc.name}.`,
  stats: [
    { val: 'iOS & Android', label: 'Cross-Platform' },
    { val: 'Flutter / React', label: 'Modern Frameworks' },
    { val: 'POPIA Ready', label: 'Enterprise Security' },
    { val: '99.9%', label: 'Cloud Reliability' }
  ],
  section2_title: `Engineered Mobile Software for ${loc.name} Innovators`,
  section2_p1: `In ${loc.name} (${loc.hub}), forward-thinking businesses and enterprise operators need robust mobile tools to connect with customers, empower field teams, and streamline core operations across ${loc.landmarks}.`,
  section2_p2: `Toran Digital engineers high-performance mobile applications using Flutter and React Native, delivering native performance on both Apple App Store and Google Play from a unified codebase.`,
  commercialFocus: loc.focus,
  suburbs: loc.suburbs,
  arterials: loc.arterials,
  mapSrc: `https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d14330.0!2d${loc.lng}!3d${loc.lat}!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x0%3A0x0!2s${encodeURIComponent(loc.name)}!5e0!3m2!1sen!2sza!4f13.1`,
  lat: loc.lat,
  lng: loc.lng,
  features: [
    { title: 'Cross-Platform Native Apps', desc: 'Single codebase targeting iOS & Android simultaneously, cutting development cost and time-to-market in half.', iconSvg: appIcon1 },
    { title: 'Robust Cloud & API Backends', desc: 'Secure Node.js/Python server architectures, AWS/Firebase cloud hosting, and real-time database sync.', iconSvg: appIcon2 },
    { title: 'POPIA & Payment Integration', desc: 'End-to-end data encryption, biometrics (FaceID/Fingerprint), and South African payment gateways (PayFast, Ozow, Peach Payments).', iconSvg: appIcon3 }
  ],
  packages: [
    { tier: 'Tier 01', name: 'MVP / Startup App', tagline: `Core feature app designed for market testing and early user validation in ${loc.name}.`, price: 'R24,500', features: ['iOS & Android App (Flutter)', 'User Authentication & Profiles', 'Core Feature Workflow', 'Cloud Database & Push Alerts', 'App Store & Google Play Submission'], popular: false },
    { tier: 'Tier 02', name: 'Enterprise App', tagline: `Full-featured commercial mobile platform with database, payment, and analytics.`, price: 'R48,500', features: ['Advanced iOS & Android Architecture', 'South African Payment Gateways', 'Real-Time Geo & Push Notifications', 'Custom Admin Dashboard Portal', 'POPIA Security & SLA Support'], popular: true },
    { tier: 'Tier 03', name: 'Custom Ecosystem', tagline: `Comprehensive multi-role mobile system with integrated APIs and hardware IoT.`, price: 'R85,000+', features: ['Multi-App Suite (Customer + Driver/Staff)', 'Complex API & ERP System Connect', 'Offline Mode with Background Sync', 'Custom Biometric & Bluetooth IoT', 'Dedicated Software Team & Roadmap'], popular: false }
  ],
  faq: [
    { q: `How much does mobile app development cost in ${loc.name}?`, a: `Our mobile app projects start from R24,500 for focused MVPs up to R48,500+ for enterprise commercial apps with payment gateways and custom backends.` },
    { q: `Do you develop for both iPhone (iOS) and Android?`, a: `Yes. We specialize in cross-platform development (Flutter and React Native), delivering native iOS and Android apps with 100% feature parity.` },
    { q: `Do you handle Apple App Store and Google Play submissions?`, a: `Yes. We handle the entire deployment process, including app signing, compliance checks, store screenshots, and store approvals.` }
  ]
}));

module.exports = { mobileAppAreas };
