const carIcon1 = `<svg fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M8 7h12m0 0l-4-4m4 4l-4 4m0 6H4m0 0l4 4m-4-4l4-4"></path></svg>`;
const carIcon2 = `<svg fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 12l2 2 4-4m5.618-4.016A11.955 11.955 0 0112 2.944a11.955 11.955 0 01-8.618 3.04A12.02 12.02 0 003 9c0 5.591 3.824 10.29 9 11.622 5.176-1.332 9-6.03 9-11.622 0-1.042-.133-2.052-.382-3.016z"></path></svg>`;
const carIcon3 = `<svg fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M17 20h5v-2a3 3 0 00-5.356-1.857M17 20H7m10 0v-2c0-.656-.126-1.283-.356-1.857M7 20H2v-2a3 3 0 015.356-1.857M7 20v-2c0-.656.126-1.283.356-1.857m0 0a5.002 5.002 0 019.288 0M15 7a3 3 0 11-6 0 3 3 0 016 0zm6 3a2 2 0 11-4 0 2 2 0 014 0zM7 10a2 2 0 11-4 0 2 2 0 014 0z"></path></svg>`;

const vehicleBrandingLocations = [
  { folder: 'vehicle-branding-jet-park', name: 'Jet Park', hub: 'Logistics & Air Freight Hub', landmarks: 'OR Tambo Airport Corridor, Kelly Road, Yaldwyn Road', arterials: 'R21 Highway, N12, Griffiths Road, Kelly Rd', lat: -26.1625, lng: 28.2389, suburbs: ['Isando', 'Bartlett', 'Witfield', 'Hughes', 'Impala Park'], focus: 'Freight forwarding trucks, airport delivery vans, logistics trailers, and intermodal transport fleets.' },
  { folder: 'vehicle-branding-isando', name: 'Isando', hub: 'Heavy Freight & Distribution Center', landmarks: 'Isando Business Park, Barbara Road, Electron Avenue', arterials: 'R24 Airport Freeway, Barbara Rd, Kraft Rd, N12', lat: -26.1361, lng: 28.2056, suburbs: ['Elandsfontein', 'Meadowdale', 'Spartan', 'Croydon', 'Kempton Park'], focus: 'Heavy commercial trucks, FMCG distribution fleets, pharmaceutical couriers, and warehouse vehicles.' },
  { folder: 'vehicle-branding-spartan', name: 'Spartan', hub: 'Industrial & Manufacturing Zone', landmarks: 'Spartan Industrial Township, Kelvin Street, Parkland Drive', arterials: 'R21 Highway, CR Swart Drive, Zuurfontein Road', lat: -26.1167, lng: 28.2167, suburbs: ['Kempton Park CBD', 'Rhodesfield', 'Chloorkop', 'Cresslawn', 'Esther Park'], focus: 'Manufacturing delivery bakkies, heavy machinery service vehicles, and trade contractor fleets.' },
  { folder: 'vehicle-branding-wadeville', name: 'Wadeville', hub: 'Heavy Industrial & Foundry Capital', landmarks: 'Wadeville Industrial Area, Dekema Road, Osborn Road', arterials: 'N3 Eastern Bypass, N17 Highway, Dekema Rd, Osborn Rd', lat: -26.2667, lng: 28.1833, suburbs: ['Roodekop', 'Alrode', 'Elsburg', 'Dinwiddie', 'Klippoortje'], focus: 'Heavy fabrication trucks, engineering service bakkies, bulk logistics trailers, and industrial tankers.' },
  { folder: 'vehicle-branding-roodekop', name: 'Roodekop', hub: 'Bulk Transport & Logistics Center', landmarks: 'Roodekop Industrial Park, Barlow Street, Nederveen Hwy', arterials: 'N3 Freeway, R103, Nederveen Highway, Osborn Road', lat: -26.3000, lng: 28.1667, suburbs: ['Wadeville', 'Leondale', 'Vosloorus', 'Alrode South', 'Rondebult'], focus: 'Long-haul freight carriers, refrigerated transport trucks, flatbed trailers, and industrial service bakkies.' },
  { folder: 'vehicle-branding-chloorkop', name: 'Chloorkop', hub: 'Chemical & Industrial Production Node', landmarks: 'Chloorkop Industrial Township, Parkland, Allandale Link', arterials: 'Allandale Road, Zuurfontein Road, Kempton-Midrand Link', lat: -26.0667, lng: 28.1667, suburbs: ['Birch Acres', 'Kempton Park West', 'Tembisa', 'Kaalfontein', 'Klipfontein'], focus: 'Hazardous chemical transport, municipal service fleets, manufacturing delivery vans, and trade bakkies.' },
  { folder: 'vehicle-branding-sebenza', name: 'Sebenza', hub: 'Light Industrial & Precision Engineering', landmarks: 'Sebenza Industrial Area, Terrace Road, Buwida Mews', arterials: 'Terrace Road, Modderfontein Road, Van Riebeeck Ave', lat: -26.1250, lng: 28.1667, suburbs: ['Edenvale', 'Eastleigh', 'Illiondale', 'Greenstone', 'Modderfontein'], focus: 'Precision engineering vans, plumbing & electrical contractor bakkies, and local delivery fleets.' },
  { folder: 'vehicle-branding-meadowdale', name: 'Meadowdale', hub: 'Commercial Distribution & Wholesale', landmarks: 'Meadowdale Mall, Herman Road, Hyperama Node', arterials: 'R24 Airport Freeway, N12, Herman Road, Edenvale Road', lat: -26.1500, lng: 28.1833, suburbs: ['Bedfordview', 'Isando', 'Primrose', 'Germiston North', 'Eastleigh'], focus: 'Wholesale distribution vans, retail delivery trucks, field technician fleets, and commercial bakkies.' },
  { folder: 'vehicle-branding-city-deep', name: 'City Deep', hub: 'Inland Container Port & Freight Terminal', landmarks: 'City Deep Container Depot, Joburg Fresh Produce Market', arterials: 'Heidelberg Road, M2 Highway, Vickers Road, N17', lat: -26.2333, lng: 28.0833, suburbs: ['Steeledale', 'Rosettenville', 'Kaserne', 'Tulisa Park', 'Moffat View'], focus: 'Intermodal container haulers, refrigerated agricultural trucks, wholesale supply vehicles, and heavy trailers.' },
  { folder: 'vehicle-branding-steeledale', name: 'Steeledale', hub: 'Steel Fabrication & Engineering District', landmarks: 'Steeledale Industrial Township, Linroy Street, Southern Klipriviersberg', arterials: 'Heidelberg Road, N12 Southern Bypass, Vickers Road', lat: -26.2500, lng: 28.0833, suburbs: ['City Deep', 'Tulisa Park', 'Oakdene', 'Electron', 'South Hills'], focus: 'Steel transport flatbeds, mobile crane trucks, industrial service bakkies, and fabrication delivery fleets.' },
  { folder: 'vehicle-branding-aeroton', name: 'Aeroton', hub: 'FMCG & High-Volume Courier Logistics', landmarks: 'Aeroton Industrial Park, Adcock Ingram Node, Nasrec Rd', arterials: 'N1 Western Bypass, M1 Highway, Golden Highway, Nasrec Rd', lat: -26.2500, lng: 27.9833, suburbs: ['Ormonde', 'Nasrec', 'Baragwanath', 'Crown Gardens', 'Robertsham'], focus: 'FMCG distribution trucks, express courier vans, pharmaceutical transport, and national delivery fleets.' },
  { folder: 'vehicle-branding-booysens', name: 'Booysens', hub: 'Industrial Repair & Manufacturing Core', landmarks: 'Booysens Reserve, Ophirton Industrial, Booysens Rd', arterials: 'M1 Highway, Booysens Road, Crownwood Road', lat: -26.2333, lng: 28.0333, suburbs: ['Ophirton', 'Turffontein', 'Robertsham', 'Selby', 'Lakeview'], focus: 'Heavy machinery repair bakkies, industrial pump service vehicles, and automotive workshop fleets.' },
  { folder: 'vehicle-branding-crown-mines', name: 'Crown Mines', hub: 'Commercial Wholesale & Trade Fleets', landmarks: 'China Mall, Crown National, Amalgam Industrial', arterials: 'M2 Highway, Main Reef Road, Crownwood Road', lat: -26.2167, lng: 28.0000, suburbs: ['Amalgam', 'Mayfair', 'Selby', 'Ormonde', 'Fordsburg'], focus: 'Wholesale merchant delivery vans, textile transport trucks, import-export cargo vehicles, and trade bakkies.' },
  { folder: 'vehicle-branding-kya-sand', name: 'Kya Sand', hub: 'Randburg Industrial & Contractor Hub', landmarks: 'Kya Sand Industrial Park, Bernie Street, Malibongwe Node', arterials: 'Malibongwe Drive (R512), Witkoppen Road, River Road', lat: -26.0167, lng: 27.9500, suburbs: ['Bloubosrand', 'North Riding', 'Cosmo City', 'Boundary Park', 'Sundowner'], focus: 'Construction contractor bakkies, solar installation fleets, industrial supply trucks, and mobile service vans.' },
  { folder: 'vehicle-branding-laser-park', name: 'Laser Park', hub: 'Roodepoort Light Industrial Park', landmarks: 'Laser Park Industrial Township, Zeiss Road, Honeydew', arterials: 'Beyers Naudé Drive, Christian de Wet Rd, Cranberry St', lat: -26.0667, lng: 27.9167, suburbs: ['Honeydew', 'Eagle Canyon', 'Radiokop', 'Wilgeheuwel', 'Strubensvalley'], focus: 'Security patrol vehicles, tech service vans, plumbing & electrical bakkies, and commercial retail fleets.' },
  { folder: 'vehicle-branding-chamdor', name: 'Chamdor', hub: 'West Rand Heavy Manufacturing Base', landmarks: 'Chamdor Industrial Park, Factoria, Luipaardsvlei', arterials: 'R28 Highway, Main Reef Road, Chamdor Road', lat: -26.1333, lng: 27.7833, suburbs: ['Krugersdorp', 'Kagiso', 'Witpoortjie', 'Factoria', 'Lewisham'], focus: 'Heavy equipment transport, mining supply trucks, beverage distribution fleets, and manufacturing bakkies.' },
  { folder: 'vehicle-branding-strydompark', name: 'Strydompark', hub: 'Automotive & Commercial Trade Center', landmarks: 'Strydompark Industrial Area, Malibongwe Commercial Strip', arterials: 'N1 Western Bypass, Malibongwe Drive, CR Swart Dr', lat: -26.0833, lng: 27.9833, suburbs: ['Ferndale', 'Bromhof', 'Fontainebleau', 'Boskruin', 'Randburg CBD'], focus: 'Automotive parts delivery vans, trade service bakkies, panel beater courtesy cars, and commercial fleets.' },
  { folder: 'vehicle-branding-silverton', name: 'Silverton', hub: 'Pretoria Automotive & Assembly Hub', landmarks: 'Ford Motor Assembly Plant, Silvertondale Industrial', arterials: 'N4 Highway, Pretoria Road, Stormvoël Road', lat: -25.7333, lng: 28.3000, suburbs: ['Silvertondale', 'Waltloo', 'Meyerspark', 'Weavind Park', 'Eersterust'], focus: 'Automotive component haulers, assembly line supply trucks, tier-1 vendor fleets, and industrial bakkies.' },
  { folder: 'vehicle-branding-rosslyn', name: 'Rosslyn', hub: 'Automotive Capital of South Africa', landmarks: 'BMW Plant Rosslyn, Nissan SA Assembly, Earnest Oppenheimer', arterials: 'R80 Mabopane Highway, R566, Platinum Highway (N4)', lat: -25.6167, lng: 28.0833, suburbs: ['Akasia', 'Karenpark', 'Ga-Rankuwa', 'Soshanguve', 'Amandasig'], focus: 'Heavy car carriers, OEM supply trucks, logistics haulers, industrial maintenance bakkies, and corporate shuttles.' },
  { folder: 'vehicle-branding-sunderland-ridge', name: 'Sunderland Ridge', hub: 'Centurion Industrial & Manufacturing Base', landmarks: 'Sunderland Ridge Industrial Park, Ellman Street', arterials: 'R55 (Main Road), M10, N14 Freeway, Mimosa Road', lat: -25.8500, lng: 28.1167, suburbs: ['Raslouw', 'Eldoraigne', 'Heuwelsig', 'Monavoni', 'Wierda Park'], focus: 'Plastics manufacturing fleets, food packaging transport, industrial trade bakkies, and delivery vans.' },
  { folder: 'vehicle-branding-hennopspark', name: 'Hennopspark', hub: 'Centurion Commercial & Trade Zone', landmarks: 'Hennopspark Industrial Area, Jacaranda Street, Old JHB Rd', arterials: 'N1 Highway, R101 (Old JHB Road), Hendrik Verwoerd Dr', lat: -25.8667, lng: 28.1667, suburbs: ['Zwartkop', 'Clubview', 'Celtisdal', 'Doringkloof', 'Amberfield'], focus: 'Commercial signage vans, HVAC contractor bakkies, security response vehicles, and local courier fleets.' },
  { folder: 'vehicle-branding-samrand', name: 'Samrand', hub: 'High-Tech Distribution & Logistics Node', landmarks: 'Samrand Business Park, Sterling Road, N1 Corridor', arterials: 'N1 Highway (Samrand Ave Exit), R101, Rooihuiskraal Rd', lat: -25.9167, lng: 28.1500, suburbs: ['Rooihuiskraal', 'The Reeds', 'Kosmosdal', 'Olievenhoutbosch', 'Midstream'], focus: 'E-commerce fulfillment vans, cold-chain refrigerated trucks, IT hardware logistics, and corporate fleet cars.' },
  { folder: 'vehicle-branding-linbro-park', name: 'Linbro Park', hub: 'Sandton Corporate Logistics Corridor', landmarks: 'Linbro Business Park, Marlboro Drive, Gautrain Depot', arterials: 'N3 Eastern Bypass, Marlboro Drive, K113', lat: -26.0833, lng: 28.1167, suburbs: ['Marlboro', 'Kelvin', 'Frankenwald', 'Modderfontein', 'Longmeadow'], focus: 'Corporate executive fleets, courier delivery vans, event staging trucks, and high-value freight vehicles.' },
  { folder: 'vehicle-branding-longmeadow', name: 'Longmeadow', hub: 'Pharmaceutical & High-Tech Distribution', landmarks: 'Longmeadow Business Estate, Modderfontein Node', arterials: 'N3 Highway, Modderfontein Road, Peace Street', lat: -26.1000, lng: 28.1333, suburbs: ['Greenstone Hill', 'Westlake', 'Lethabong', 'Edenvale North', 'Thornhill'], focus: 'Pharmaceutical cold-chain vans, electronics distribution trucks, corporate service vehicles, and trade fleets.' },
  { folder: 'vehicle-branding-wynberg', name: 'Wynberg', hub: 'Sandton Commercial & Light Industrial', landmarks: 'Wynberg Industrial Area, 5th Street Strip, Grayston Node', arterials: 'M1 Highway (Grayston Dr Exit), Pretoria Main Rd, Katherine St', lat: -26.1000, lng: 28.0833, suburbs: ['Sandown', 'Kramerville', 'Bramley', 'Alexandra', 'Inanda'], focus: 'Textile delivery vans, catering & hospitality trucks, film production vehicles, and commercial bakkies.' },
  { folder: 'vehicle-branding-kramerville', name: 'Kramerville', hub: 'Design, Décor & Delivery Hub', landmarks: 'Kramerville Design District, Desmond Street, Sandton East', arterials: 'M1 Highway, Marlboro Drive, Katherine Street', lat: -26.0917, lng: 28.0833, suburbs: ['Morningside', 'Gallo Manor', 'Eastgate Sandton', 'Sandhurst', 'Rivonia'], focus: 'High-end furniture delivery trucks, interior design studio vans, luxury showroom shuttles, and trade bakkies.' },
  { folder: 'vehicle-branding-heidelberg', name: 'Heidelberg', hub: 'N3 Transport Corridor & Agro-Industrial', landmarks: 'Heidelberg Industrial, Shalimar Ridge, N3 Toll Route', arterials: 'N3 National Highway, R23, R42, Voortrekker Street', lat: -26.5000, lng: 28.3500, suburbs: ['Rensburg', 'Bergsig', 'Jordan Park', 'Ratanda', 'Overkruin'], focus: 'Long-haul interstate freight trucks, agricultural transport, fuel tankers, and construction bakkies.' },
  { folder: 'vehicle-branding-springs', name: 'Springs', hub: 'Heavy Industrial & Manufacturing Fleets', landmarks: 'Nuffield Industrial, New Era, Springs Fresh Market', arterials: 'N17 Highway, R51, Wit Road, Welgedacht Road', lat: -26.2500, lng: 28.4333, suburbs: ['Nuffield', 'New Era', 'Selection Park', 'Strubenvale', 'Geduld'], focus: 'Heavy metal fabricator trucks, raw material transporters, industrial chemical carriers, and trade bakkies.' },
  { folder: 'vehicle-branding-brakpan', name: 'Brakpan', hub: 'East Rand Contracting & Trade Bakkies', landmarks: 'Vulcania Industrial, Apex, Carnival Commercial Zone', arterials: 'N17 Highway, R23, Voortrekker Road, Prince George Ave', lat: -26.2361, lng: 28.3694, suburbs: ['Vulcania', 'Apex', 'Dalview', 'Helderwyk', 'Brenthurst'], focus: 'Electrical contractor bakkies, mining equipment service vehicles, local delivery trucks, and commercial vans.' },
  { folder: 'vehicle-branding-nigel', name: 'Nigel', hub: 'Rail & Heavy Engineering Center', landmarks: 'Pretoriusstad Industrial, Gibela Rail Manufacturing', arterials: 'R42, R51, Balfour Road, Nigel-Springs Road', lat: -26.4333, lng: 28.4667, suburbs: ['Pretoriusstad', 'Ferryvale', 'Glenvarloch', 'Duduza', 'Vischkuil'], focus: 'Rail engineering transport, heavy manufacturing fleets, agricultural service bakkies, and equipment trucks.' },
  { folder: 'vehicle-branding-randfontein', name: 'Randfontein', hub: 'West Rand Mining & Agricultural Fleets', landmarks: 'Aureus Industrial, Elandsvlei, Main Reef Road', arterials: 'R28 Freeway, R41, Main Reef Road, Village Street', lat: -26.1833, lng: 27.7000, suburbs: ['Aureus', 'Greenhills', 'Homelake', 'Helikon Park', 'Culemborg Park'], focus: 'Mining machinery transport, grain and livestock trucks, engineering service bakkies, and municipal vehicles.' },
  { folder: 'vehicle-branding-vanderbijlpark', name: 'Vanderbijlpark', hub: 'Steel City Heavy Plant & Industrial', landmarks: 'ArcelorMittal Steel Complex, NW7 Industrial, Frikkie Meyer', arterials: 'R59 Sybrand van Niekerk Freeway, R57, Barrage Road', lat: -26.7000, lng: 27.8333, suburbs: ['NW7 Industrial', 'CE6', 'SW5', 'Flora Gardens', 'Bophelong'], focus: 'Heavy steel transport trucks, industrial plant service bakkies, chemical tankers, and engineering fleets.' },
  { folder: 'vehicle-branding-vereeniging', name: 'Vereeniging', hub: 'Vaal Commercial & Transport Core', landmarks: 'Duncanville Industrial, Powerville, River Square', arterials: 'R59 Freeway, R82 (Old JHB Rd), General Smuts Rd', lat: -26.6667, lng: 27.9333, suburbs: ['Duncanville', 'Powerville', 'Three Rivers', 'Peacehaven', 'Falcon Ridge'], focus: 'Commercial distribution trucks, trade contractor bakkies, agricultural logistics vehicles, and delivery vans.' },
  { folder: 'vehicle-branding-meyerton', name: 'Meyerton', hub: 'Midvaal Manufacturing & Agri-Hub', landmarks: 'Meyerton Industrial Area, Ncaneng, Pierneef Blvd', arterials: 'R59 Freeway, Johan Le Roux Road, Meyer Street', lat: -26.5833, lng: 28.0167, suburbs: ['Rothdene', 'Kookrus', 'Golf Park', 'Henley on Klip', 'Sicelo'], focus: 'Manufacturing delivery trucks, agri-business service bakkies, transport trailers, and trade fleet vehicles.' },
  { folder: 'vehicle-branding-alberton-north', name: 'Alberton North', hub: 'Trade & Commercial Workshop Center', landmarks: 'Alberton North Industrial, Van Dyk Road, Piet Retief', arterials: 'N12 Freeway, Voortrekker Road, Ring Road East', lat: -26.2556, lng: 28.1250, suburbs: ['Florentia', 'Alrode', 'Newmarket', 'Raceview', 'Verwoerdpark'], focus: 'Auto body shop courtesy fleets, trade specialist bakkies, industrial tool delivery vans, and commercial trucks.' }
];

const vehicleBrandingAreas = vehicleBrandingLocations.map(loc => ({
  folder: loc.folder,
  locality: loc.name,
  serviceName: 'Vehicle Branding',
  serviceBadge: 'Fleet Wrapping Studio',
  title: `Vehicle Branding ${loc.name} | Toran Digital`,
  desc: `Commercial vehicle branding, bakkie wraps, and fleet graphics in ${loc.name}. 3M & Avery Dennison cast vinyl with 5-7 year warranty.`,
  h1_prefix: `High-Impact Vehicle Branding in`,
  h1_highlight: loc.name,
  hero_desc: `Transform your commercial bakkies, trucks, and company fleet into high-visibility moving billboards across ${loc.name} and Gauteng's busiest industrial corridors.`,
  stats: [
    { val: '5-7 Yrs', label: 'Vinyl Durability' },
    { val: '3M / Avery', label: 'Premium Cast Films' },
    { val: '30k-70k', label: 'Daily Brand Views' },
    { val: '100%', label: 'UV & Scratch Proof' }
  ],
  section2_title: `Turn Your ${loc.name} Fleet Into Moving Billboards`,
  section2_p1: `In ${loc.name} (${loc.hub}), hundreds of thousands of commercial decision-makers and consumers travel along ${loc.arterials} every day around ${loc.landmarks}. Unbranded vehicles represent lost marketing opportunities.`,
  section2_p2: `At Toran Digital, we design, print, and install high-durability cast vinyl wraps engineered to withstand South Africa’s harshest UV radiation, road grit, and daily industrial wash cycles across ${loc.name}.`,
  commercialFocus: loc.focus,
  suburbs: loc.suburbs,
  arterials: loc.arterials,
  mapSrc: `https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d14330.0!2d${loc.lng}!3d${loc.lat}!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x0%3A0x0!2s${encodeURIComponent(loc.name)}!5e0!3m2!1sen!2sza!4f13.1`,
  lat: loc.lat,
  lng: loc.lng,
  features: [
    { title: 'Premium 3M & Avery Cast Vinyl', desc: 'Conformable high-grade cast vinyl that hugs every body contour without peeling, bubbling, or fading.', iconSvg: carIcon2 },
    { title: 'Custom In-House Design', desc: 'Our graphic designers tailor high-contrast, professional visual layouts optimized for maximum legibility at highway speeds.', iconSvg: carIcon1 },
    { title: 'Fleet Deployment & On-Site Wrap', desc: 'Scheduled staggered installations or mobile installation at your premises in ${loc.name} to minimize fleet downtime.', iconSvg: carIcon3 }
  ],
  packages: [
    { tier: 'Tier 01', name: 'Decals & Spot Graphics', tagline: `Essential branding package for ${loc.name} trade bakkies and delivery runabouts.`, price: 'R2,950', features: ['Door Logos & Phone Numbers', 'Rear Tailgate Branding', 'One-Way Vision Rear Window', 'High-Gloss UV Laminate', '3-Year Vinyl Warranty'], popular: false },
    { tier: 'Tier 02', name: 'Half / Partial Wrap', tagline: `Most popular branding choice for commercial fleets across ${loc.name}.`, price: 'R7,800', features: ['Rear Half Body Wrap', 'High-Impact Digital Graphics', 'Hood / Bonnet Logo Included', '5-Year Cast Film Warranty', 'Scratch-Resistant Lamination'], popular: true },
    { tier: 'Tier 03', name: 'Full Fleet Wrap', tagline: `Maximum brand dominance for trucks, bakkies, and corporate delivery fleets.`, price: 'R14,500', features: ['100% Full Body Wrap Coverage', 'Avery Dennison / 3M Cast Vinyl', 'Color Transformation & Protection', 'Fleet Volume Discount Available', '7-Year Durability Guarantee'], popular: false }
  ],
  faq: [
    { q: `How long will a vehicle wrap last in ${loc.name}?`, a: `Our premium Avery Dennison and 3M cast vinyl wraps last between 5 to 7 years under harsh South African sunlight and daily industrial driving conditions.` },
    { q: `Can you brand multiple fleet vehicles at our premises in ${loc.name}?`, a: `Yes. We provide on-site mobile installation for commercial fleets across ${loc.name} and surrounding industrial parks to prevent operational disruption.` },
    { q: `Will vehicle wrapping damage the original vehicle paint?`, a: `No. In fact, automotive vinyl wraps protect original OEM factory paintwork from stone chips, scratches, and UV weathering, preserving resale value.` }
  ]
}));

module.exports = { vehicleBrandingAreas };
